### ISSUE TITLE
Physical security - Umbrella 

### ISSUE THREAD

**Issue by bact** [mishari/th-digital-survival#12]
ใน https://secfirst.org/umbrella/ มีคำแนะนำเรื่องความปลอดภัยทางกายภาพด้วย (มีทั้งเรื่องดิจิทัล กายภาพ จิตวิทยา ฯลฯ)

ถ้าใจอยากแปล ไปกด join team ได้ในนี้ครับ
https://www.transifex.com/otf/umbrella-project/dashboard/

**Comment by mishari** [comment]
ถ้างั้นเราเอาเป็น Meta issue เลยดีกว่า ถ้ามีทรัพยากรและเครื่องมือที่ดีอยู่แล้ว เราควรรวบรวมอาสาสมัครและแปลของเขา มาทำเป็นโปรเจ็กต์เลยดีไหม?

**Comment by bact** [comment]
ลองชวนๆ ดู

**Comment by mishari** [comment]
Creating a new meta issue that includes this.
