### ISSUE TITLE
Sample IPv6 address collision with Markdown Emoji

### ISSUE THREAD

**Issue by krissdap** [mishari/th-digital-survival#14]
The : 1234 : is an emoji for markdown.

<img width="551" alt="markdown-1234" src="https://user-images.githubusercontent.com/5546755/76309252-ffbccd00-62fe-11ea-835b-1b64df9f72a1.png">

Let's change the number.

**Comment by mishari** [comment]
Thank you, I didn't know what was happening, fixed.
